UserProject/Controllers/AddProjectsController.cs
using BLL;
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UserProject.Controllers
{
    public class AddProjectsController : Controller
    {
        // GET: AddProjects
        public ActionResult Index()
        {
            AddProjectBLL addProjectBLL = new AddProjectBLL();
            List<AddProjects> addProjects = addProjectBLL.addProjects().ToList();
            return View(addProjects);
        }

        public ActionResult Details(int Id)
        {
            AddProjectBLL addProjectBLL = new AddProjectBLL();
            return View(addProjectBLL.addProjects().Find(ur => ur.Id == Id));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(AddProjects addProject)
        {
            AddProjectBLL addProjectBLL = new AddProjectBLL();
            var insert = addProjectBLL.CreateProject(addProject);
            if (insert)
            {
                ViewBag.Message = "Project Added";
            }
            return RedirectToAction("Create");
        }

        public ActionResult Edit(int Id)
        {
            AddProjectBLL addProjectBLL = new AddProjectBLL();
            return View(addProjectBLL.addProjects().Find(ur => ur.Id == Id));
        }

        // POST: AddProject/Edit/5
        [HttpPost]
        public ActionResult Edit(int Id, AddProjects ap)
        {
            AddProjectBLL addProjectBLL = new AddProjectBLL();
            try
            {
                // TODO: Add update logic here
                if (addProjectBLL.UpdateProject(ap))
                {
                    ViewBag.Message = "Project Updated";
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int Id)
        {
            AddProjectBLL addProjectBLL = new AddProjectBLL();
            return View(addProjectBLL.addProjects().Find(ur => ur.Id == Id));
        }

        // POST: AddProject/Delete/5
        [HttpPost]
        public ActionResult Delete(int Id, AddProjects ap)
        {
            AddProjectBLL addProjectBLL = new AddProjectBLL();
            try
            {
                // TODO: Add delete logic here
                if (addProjectBLL.DeleteProject(ap))
                {
                    ViewBag.Message = "Project Added";
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

UserProject/Views/AddProjects/Create.cshtml
@model DAL.AddProjects

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "AddProjects", FormMethod.Post, new { @id = "AddProjectCreate", @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
<div class="form-horizontal">
    <h4>AddProject</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProjectStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProjectStartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProjectStartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProjectEndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProjectEndDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProjectEndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" for="customRange3">
        @Html.LabelFor(model => model.projectPriority, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.projectPriority, new { htmlAttributes = new { @type = "range", @min = "0", @max = "3", @step = "1", @class = "form-control-range", @id = "customRange3" } })
            @Html.ValidationMessageFor(model => model.projectPriority, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmpId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EmpId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EmpId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add Project" class="btn btn-default" />
            <input type="reset" value="Reset" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/custom-validator")
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#AddProjectCreate').validate({
                errorClass: 'help-block animation-slideDown', // You can change the animation class for a different entrance animation - check animations page
                errorElement: 'div',
                errorPlacement: function (error, e) {
                    e.parents('.form-group > div').append(error);
                },
                highlight: function (e) {

                    $(e).closest('.form-group').removeClass('has-success has-error').addClass('has-error');
                    $(e).closest('.help-block').remove();
                },
                success: function (e) {
                    e.closest('.form-group').removeClass('has-success has-error');
                    e.closest('.help-block').remove();
                },
                rules: {
                    'ProjectName': {
                        required: true
                    },

                    'ProjectStartDate': {
                        required: true
                    },

                    'ProjectEndDate': {
                        required: true
                    },

                    'projectPriorityp': {
                        required: true
                    },

                    'FirstName': {
                        required: true
                    },
                    'EmpId': {
                        required: true
                    }


                },
                messages: {
                    'ProjectName': {
                        required: 'Project Name is Required'
                    },

                    'ProjectStartDate': {
                        required: 'Project Start Date  is Required'
                    },

                    'ProjectEndDate': {
                        required: 'Project Start Date is Required'
                    },
                    'projectPriorityp': {
                        required: 'Project Priority is Required',
                    },
                    'FirstName': {
                        required: 'First Name Id is Required'
                    },
                    'EmpId': {
                        required: 'Emp Id Name Id is Required'
                    }
                }
            });
        });
    </script>
}

UserProject/Views/AddProjects/Delete.cshtml
@model DAL.AddProjects

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AddProjects</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectEndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectEndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectPriority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectPriority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UserProject/Views/AddProjects/Details.cshtml
@model DAL.AddProjects

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AddProjects</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectEndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectEndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectPriority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectPriority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UserProject/Views/AddProjects/Edit.cshtml
@model DAL.AddProjects

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>AddProjects</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProjectStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProjectStartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProjectStartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProjectEndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProjectEndDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProjectEndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" for="customRange3">
        @Html.LabelFor(model => model.projectPriority, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.projectPriority, new { htmlAttributes = new { @type = "range", @min = "0", @max = "3", @step = "1", @class = "form-control-range", @id = "customRange3" } })
            @Html.ValidationMessageFor(model => model.projectPriority, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmpId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EmpId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EmpId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

UserProject/Views/AddProjects/Index.cshtml
@model IEnumerable<DAL.AddProjects>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProjectStartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProjectEndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.projectPriority)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmpId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.ProjectName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ProjectStartDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ProjectEndDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.projectPriority)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.EmpId)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
    </td>
</tr>
}

</table>